# Generated by Django 6.0.3 on 2026-04-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Making Charges',
                'verbose_name_plural': 'Making Charges',
            },
        ),
        migrations.CreateModel(
            name='TaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='goldrate',
            options={'verbose_name': 'Gold Rate', 'verbose_name_plural': 'Gold Rates'},
        ),
        migrations.AddField(
            model_name='goldrate',
            name='purity',
            field=models.CharField(choices=[('22K', '22K'), ('24K', '24K')], default=22, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goldrate',
            name='rate_per_gram',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
