# Generated by Django 6.0.3 on 2026-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate', '0002_makingcharges_taxconfig_alter_goldrate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_22k', models.FloatField()),
                ('gold_24k', models.FloatField()),
                ('gst_percent', models.FloatField()),
                ('making_charge', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.DeleteModel(
            name='GoldRate',
        ),
        migrations.DeleteModel(
            name='MakingCharges',
        ),
        migrations.DeleteModel(
            name='TaxConfig',
        ),
    ]
